<?php

class CT_CtTabs_Widget extends Case_Theme_Core_Widget_Base{
    protected $name = 'ct_tabs';
    protected $title = 'Tabs';
    protected $icon = 'eicon-tabs';
    protected $categories = array( 'case-theme-core' );
    protected $params = '{"sections":[{"name":"section_tabs","label":"Tabs","tab":"content","controls":[{"name":"active_tab","label":"Active Tab","type":"number","default":1,"separator":"after"},{"name":"tabs","label":"Tabs Items","type":"repeater","controls":[{"name":"ct_icon","label":"Icon","type":"icons","fa4compatibility":"icon"},{"name":"tab_title","label":"Title","type":"text","default":"Tab Title","placeholder":"Tab Title","label_block":true},{"name":"content_type","label":"Content Type","type":"select","default":"text_editor","options":{"text_editor":"Text Editor","template":"Template","form":"Contact Form 7"}},{"name":"tab_content","label":"Content","type":"wysiwyg","default":"Tab Content","placeholder":"Tab Content","show_label":false,"condition":{"content_type":"text_editor"}},{"name":"tab_content_template","label":"Template","type":"select","default":"","options":{"":"Select Template","6131":"agile","6058":"singleservice","6019":"servicesv1","6013":"About","5947":"old home","5499":"Default Kit","4540":"Default Kit","3872":"Pricing - Year Style 2","3876":"Pricing - Month Style 2","2331":"Tab 01","1217":"Pricing - Year","1214":"Pricing - Month"},"condition":{"content_type":"template"}},{"name":"form_id","label":"Select Contact Form 7","type":"select","options":{"6":"Contact form 1","5244":"Home Contact Form Step","5005":"Contact Version 1","5003":"Contact Version 3","3851":"Contact Version 4","3823":"Contact Version 2","1615":"FAQ","91":"Main Contact Form"},"condition":{"content_type":"form"}}],"title_field":"{{{ tab_title }}}"},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .ct-tabs--layout1.style3 .ct-tab-title":"color: {{VALUE}};"},"condition":{"tab_style":"style3"}},{"name":"content_color","label":"Content Color","type":"color","selectors":{"{{WRAPPER}} .ct-tabs--layout1.style3 .ct-tab-content":"color: {{VALUE}};"},"condition":{"tab_style":"style3"}},{"name":"tab_type","label":"Type","type":"select","options":{"horizontal":"Horizontal","vertical":"Vertical"},"default":"horizontal"},{"name":"title_color_type","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .ct-tabs--layout2.type-vertical .ct-tab-title":"color: {{VALUE}};","{{WRAPPER}} .ct-tabs--layout2.type-vertical .ct-tabs-title":"border-color: {{VALUE}};","{{WRAPPER}} .ct-tabs--layout2.type-vertical .ct-tab-title i:before":"background-color: {{VALUE}};"},"condition":{"tab_type":"vertical"}},{"name":"content_color_type","label":"Content Color","type":"color","selectors":{"{{WRAPPER}} .ct-tabs--layout2.type-vertical .ct-tab-content":"color: {{VALUE}};"},"condition":{"tab_type":"vertical"}},{"name":"tab_style","label":"Style","type":"select","options":{"style1":"Style 1","style2":"Style 2 (Radio \/ Only 2 items)","style3":"Style 3","style4":"Style 4"},"default":"style1","condition":{"tab_type":"horizontal"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'ct-tabs-widget-js' );
}